spring.application.name=mundial2026hub

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mundial2026hub
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=mundial2026hubSecretKey12345678901234
jwt.expiration=86400000

# Puerto del servidor
server.port=8080

# Configuracion SMTP (Gmail)
# IMPORTANTE: Reemplaza con tu correo y contrasena de aplicacion de Gmail
# Para obtener contrasena de aplicacion: Cuenta Google > Seguridad > Verificacion en 2 pasos > Contrasenas de aplicacion
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=proyectosoftware0@gmail.com
spring.mail.password=isok nwcc vmao jfzq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# URL base del frontend (para enlaces en correos)
app.frontend.url=http://localhost:3000
